/*
 * @Author: wxfeiang
 * @Description: 自动导入的文件列表
 * @Date: 2023-05-03 11:56:13
 * @LastEditTime: 2023-05-03 11:59:13
 * @FilePath: /vue3template/components.d.ts
 */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    Menu: typeof import('./src/components/menu.tsx')['default'];
  }
}
